[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self' https://telegram.org; script-src 'self' https://telegram.org https://core.telegram.org 'unsafe-inline'; style-src 'self' 'unsafe-inline'; connect-src 'self' https://api.coingecko.com; img-src 'self' data: https: http: blob:; font-src 'self' data:;"
    X-Frame-Options = "ALLOWALL"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200